name: Schedule Subscribe
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  subscribe:
    name: "Subscribe"
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: yarn install
      - name: Subscribe
        run: |
          npm run add-subscription-to-inoreader
        env:
          INOREADER_TOKEN_JSON: ${{ secrets.INOREADER_TOKEN_JSON }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
